applications:
  helloworld:
    namespace: argocd
    project: aoa
    source:
      repoURL: https://github.com/taylorshaulis/public.git
      targetRevision: HEAD
      path: charts/helloworld
    destination:
      server: https://kubernetes.default.svc
      namespace: helloworld
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true
      syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  # kyverno:
  #   namespace: argocd
  #   project: aoa
  #   source:
  #     repoURL: https://kyverno.github.io/kyverno
  #     targetRevision: 3.2.4
  #     chart: kyverno
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: kyverno
  #   syncPolicy:
  #     automated:
  #       prune: true
  #       selfHeal: true
  #       allowEmpty: true
  #     syncOptions:
  #     - CreateNamespace=true
  #     - PruneLast=true
  #     - Replace=true
  # crossplane:
  #   namespace: argocd
  #   project: aoa
  #   source:
  #     repoURL: https://kyverno.github.io/kyverno
  #     targetRevision: 3.2.4
  #     chart: kyverno
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: kyverno
  #   syncPolicy:
  #     automated:
  #       prune: true
  #       selfHeal: true
  #       allowEmpty: true
  #     syncOptions:
  #     - CreateNamespace=true
  #     - PruneLast=true

projects:
  aoa:
    namespace: argocd
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    sourceNamespaces:
    - argocd
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
#  guestbook:
#    namespace: argocd
#    additionalLabels: {}
#    additionalAnnotations: {}
#    permitOnlyProjectScopedClusters: false
#    finalizers:
#    - resources-finalizer.argocd.argoproj.io
#    description: Example Project
#    sourceRepos:
#    - '*'
#    destinations:
#    - namespace: guestbook
#      server: https://kubernetes.default.svc
#    clusterResourceWhitelist: []
#    clusterResourceBlacklist: []
#    namespaceResourceBlacklist:
#    - group: ''
#      kind: ResourceQuota
#    - group: ''
#      kind: LimitRange
#    - group: ''
#      kind: NetworkPolicy
#      orphanedResources: {}
#      roles: []
#    namespaceResourceWhitelist:
#    - group: 'apps'
#      kind: Deployment
#    - group: 'apps'
#      kind: StatefulSet
#    orphanedResources: {}
#    roles: []
#    syncWindows:
#    - kind: allow
#      schedule: '10 1 * * *'
#      duration: 1h
#      applications:
#      - '*-prod'
#      manualSync: true
#    signatureKeys:
#    - keyID: ABCDEF1234567890
#    sourceNamespaces:
#    - argocd