applications:
  helloworld:
    namespace: argocd
    project: aoa
    source:
      repoURL: https://github.com/taylorshaulis/public.git
      targetRevision: HEAD
      path: charts/helloworld
    destination:
      server: https://kubernetes.default.svc
      namespace: helloworld
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true
      syncOptions:
      - CreateNamespace=true
      - PruneLast=true
#  guestbook:
#    namespace: argocd
#    additionalLabels: {}
#    additionalAnnotations: {}
#    finalizers:
#    - resources-finalizer.argocd.argoproj.io
#    project: guestbook
#    source:
#      repoURL: https://github.com/argoproj/argocd-example-apps.git
#      targetRevision: HEAD
#      path: guestbook
#      directory:
#        recurse: true
#    # ArgoCD v2.6 or later
#    sources:
#    - chart: elasticsearch
#      repoURL: https://helm.elastic.co
#      targetRevision: 8.5.1
#    - repoURL: https://github.com/argoproj/argocd-example-apps.git
#      path: guestbook
#      targetRevision: HEAD
#    destination:
#      server: https://kubernetes.default.svc
#      namespace: guestbook
#    syncPolicy:
#      automated:
#        prune: false
#        selfHeal: false
#      syncOptions:
#      - CreateNamespace=true
#    revisionHistoryLimit: null
#    ignoreDifferences:
#    - group: apps
#      kind: Deployment
#      jsonPointers:
#      - /spec/replicas
#    info:
#    - name: url
#      value: https://argoproj.github.io/

projects:
  aoa:
    namespace: argocd
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    sourceNamespaces:
    - argocd
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
#  guestbook:
#    namespace: argocd
#    additionalLabels: {}
#    additionalAnnotations: {}
#    permitOnlyProjectScopedClusters: false
#    finalizers:
#    - resources-finalizer.argocd.argoproj.io
#    description: Example Project
#    sourceRepos:
#    - '*'
#    destinations:
#    - namespace: guestbook
#      server: https://kubernetes.default.svc
#    clusterResourceWhitelist: []
#    clusterResourceBlacklist: []
#    namespaceResourceBlacklist:
#    - group: ''
#      kind: ResourceQuota
#    - group: ''
#      kind: LimitRange
#    - group: ''
#      kind: NetworkPolicy
#      orphanedResources: {}
#      roles: []
#    namespaceResourceWhitelist:
#    - group: 'apps'
#      kind: Deployment
#    - group: 'apps'
#      kind: StatefulSet
#    orphanedResources: {}
#    roles: []
#    syncWindows:
#    - kind: allow
#      schedule: '10 1 * * *'
#      duration: 1h
#      applications:
#      - '*-prod'
#      manualSync: true
#    signatureKeys:
#    - keyID: ABCDEF1234567890
#    sourceNamespaces:
#    - argocd