apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Values.name }}
spec:
  containers:
    - name: test
      image: busybox
      command: ["/bin/sh"]
      args: ["-c","while true; do echo hello; sleep 1000;done"]
