apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: registry.k8s.io/busybox
      command: ["/bin/sh"]
      args: ["-c","while true; do echo hello; sleep 1000;done"]
